name: make docker-compose-development

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      matrix:
        version: ['20.04']
    runs-on: ubuntu-${{ matrix.version }}
    name: Ubuntu ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Update APT repositories
        run: sudo apt update -y
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Docker Compose Development
        run: make docker-compose-development INTERACTIVE=0
